// TDW/module2-react/theoretical-essay/qwik-counter-app/src/components/button/index.tsx
import { component$, PropFunction, useStylesScoped$ } from "@builder.io/qwik";
import styles from './button.css?inline';

interface ButtonType {
    label: string,
    onClick$: PropFunction<() => void>
}

const Button = component$((props: ButtonType) => {
    useStylesScoped$(styles)

    return (
        <button class='btn' onClick$={props.onClick$}>{props.label}</button>
    )
})

export default Button

// TDW/module2-react/theoretical-essay/react-counter-app/src/components/Button/index.tsx
import React, { MouseEventHandler } from 'react';
import "./button.css";

interface ButtonType {
    label: string
    onClick: MouseEventHandler
}

const Button = (props: ButtonType) => {
    return (
        <button onClick={props.onClick} className='btn'>{props.label}</button>
    )
}

export default Button
